### ISSUE TITLE
Not able to upload file by using dropbox on cordova app based on meteor

### ISSUE THREAD

**Issue by prachi708** [dropbox/cordova-datastores-example#4]
I want to use dropbox to upload files on my cordova app based on meteor i.e., user will be given option if he wants to upload file using dropbox if user click on the button then inappbrowser should open from where user will be authenticated and can upload file. 

I am using  
          <  script type="text/javascript"       src="https://www.dropbox.com/static/api/2/dropins.js" id="id_dropbox" data-app-key="xxxxxxxxxxx"></script> 
      this script. 

This is the code  

       e.preventDefault();
         Dropbox.choose({
            linkType: "direct",
            multiselect: false,
            extensions: ['.doc'],
            success: function(files) {
                console.log("files ", files[0]);
                if(files[0]['bytes']<1000000){
                	GetBlobDataDropbox(files)    //function to upload file
                }else{
                	alert('Size should be less than 1 mb')
                } 
       },
            error:function(error){console.log(error)},
            cancel:  function() {}
        }); `

This is giving me error "maximum call stack size exceded". please tell how to resolve it. 
P.S.: this code is working fine for webapp.

**Comment by greg-db** [comment]
It looks like you're using [the Dropbox Chooser](https://www.dropbox.com/developers/chooser), which is unrelated to [this cordova-datastores-example repo](https://github.com/dropbox/cordova-datastores-example) where you posted this issue.

In any case, the error message you shared indicates that you've created too large of a call stack. (For example, one way to do this is by recursively calling a function within itself.)

That error isn't related to Dropbox or the Dropbox Chooser itself, so I'm afraid I can't be of much help. You'll need to debug the code in your app to see why you're creating a large call stack.
